command: ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: CATALOG_NAME
    value: "lr_serverless_aws_us_catalog"
  - name: SCHEMA_NAME
    value: "solvency2demo"
  - name: WAREHOUSE_ID
    value: "c80acfa212bf1166"
  - name: DASHBOARD_ID
    value: "01f1244c1206118fb4cfdf90f7c9dbfb"
  - name: GENIE_SPACE_ID
    value: "01f1244a47ff19aabdc79f1c050bbc16"
