command: ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: CATALOG_NAME
    value: "lr_serverless_aws_us_catalog"
  - name: SCHEMA_NAME
    value: "solvency2demo"
  - name: WAREHOUSE_ID
    value: "c80acfa212bf1166"
  - name: DASHBOARD_ID
    value: "01f1245237931a22beda7389a60b22b8"
  - name: GENIE_SPACE_ID
    value: "01f126e511aa173e88fa7540c232f864"
