command: ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: CATALOG_NAME
    value: "lr_serverless_aws_us_catalog"
  - name: SCHEMA_NAME
    value: "solvency2demo"
  - name: WAREHOUSE_ID
    value: "c80acfa212bf1166"
  - name: DASHBOARD_ID
    value: "01f1243a2e2b109cad920b69228a73cd"
  - name: GENIE_SPACE_ID
    value: "01f12449a1221505b647e252c7f537ae"
